 
#define LAMP_HEAD_SHOOT_AGAIN       0
#define LAMP_HEAD_BALL_IN_PLAY      1
#define LAMP_HEAD_TILT              2
#define LAMP_HEAD_GAME_OVER         3
#define LAMP_HEAD_MATCH             4
#define LAMP_HEAD_HIGH_SCORE_TO_DATE  5
#define LAMP_APRON_CREDITS          6
#define LAMP_HEAD_TIMER_BONUS_BALL  7
#define LAMP_RIGHT_MAGNASAVE        8
#define LAMP_LEFT_MAGNASAVE         9
#define LAMP_LEFT_OUTLANE           10
#define LAMP_RIGHT_OUTLANE          11
#define LAMP_SPINNER                12
#define LAMP_MIDDLE_RAMP            13
#define LAMP_RIGHT_INLANE           14
#define LAMP_LEFT_INLANE            15
#define LAMP_LOWER_LEFT_DROPS       16
#define LAMP_LOWER_RIGHT_DROPS      17
#define LAMP_UPPER_LEFT_DROPS       18
#define LAMP_UPPER_RIGHT_DROPS      19
#define LAMP_LOCK_2                 20
#define LAMP_LOOP_SPECIAL           21
#define LAMP_LOOP_EXTRA_BALL        22
#define LAMP_SAUCER                 23
#define LAMP_LLDROPS_1              24
#define LAMP_LLDROPS_2              25
#define LAMP_LLDROPS_3              26
#define LAMP_DOUBLE_SCORING         27
#define LAMP_LRDROPS_3              28
#define LAMP_LRDROPS_2              29
#define LAMP_LRDROPS_1              30
#define LAMP_TRIPLE_SCORING         31
#define LAMP_ULDROPS_3              32
#define LAMP_ULDROPS_2              33
#define LAMP_ULDROPS_1              34
#define LAMP_POP_BUMPER             35
#define LAMP_URDROPS_3              36
#define LAMP_URDROPS_2              37
#define LAMP_URDROPS_1              38
#define LAMP_LOCK_3                 39
#define LAMP_UPPER_EXTRA_BALL       40
#define LAMP_LOCK_1                 41

#define LAMP_SHOOT_AGAIN            46
#define LAMP_BONUS_1                47
#define LAMP_BONUS_2                48
#define LAMP_BONUS_3                49
#define LAMP_BONUS_4                50
#define LAMP_BONUS_5                51
#define LAMP_BONUS_6                52
#define LAMP_BONUS_7                53
#define LAMP_BONUS_8                54
#define LAMP_BONUS_9                55
#define LAMP_BONUS_10               56
#define LAMP_BONUS_20               57
#define LAMP_BONUS_30               58
#define LAMP_BONUS_40               59
#define LAMP_2X                     60
#define LAMP_3X                     61
#define LAMP_4X                     62
#define LAMP_5X                     63


#define SW_PLUMB_TILT             0
#define SW_ROLL_TILT              1
#define SW_CREDIT_RESET           2
#define SW_COIN_1                 3
#define SW_COIN_2                 4
#define SW_COIN_3                 5
#define SW_SLAM                   6
#define SW_HIGH_SCORE_RESET       7 
#define SW_RIGHT_MAGNET_BUTTON    8
#define SW_LEFT_MAGNET_BUTTON     9
#define SW_LEFT_OUTLANE           10
#define SW_RIGHT_OUTLANE          11
#define SW_SPINNER                12
#define SW_RIGHT_RAMP_ROLLUNDER   13
#define SW_RIGHT_INSIDE_ROLLOVER  14
#define SW_LEFT_INSIDE_ROLLOVER   15
#define SW_RIGHT_BALL_RAMP        16
#define SW_CENTER_BALL_RAMP       17
#define SW_LEFT_BALL_RAMP         18
#define SW_OUTHOLE                19
#define SW_LEFT_SLING             20
#define SW_RIGHT_SLING            21
#define SW_LOOP                   22
#define SW_SAUCER                 23
#define SW_LL_DROP_1              24
#define SW_LL_DROP_2              25
#define SW_LL_DROP_3              26
#define NO_SW_LL_DROP_STANDUP     27
#define SW_LR_DROP_3              28
#define SW_LR_DROP_2              29
#define SW_LR_DROP_1              30
#define NO_SW_LR_DROP_STANDUP     31
#define SW_UL_DROP_1              32
#define SW_UL_DROP_2              33
#define SW_UL_DROP_3              34
#define SW_POP_BUMPER             35
#define SW_UR_DROP_1              36
#define SW_UR_DROP_2              37
#define SW_UR_DROP_3              38
#define NO_SW_UR_DROP_STANDUP     39
#define SW_LOCK_1                 40
#define SW_LOCK_2                 41
#define SW_LOCK_3                 42
#define SW_LEFT_RAMP_ROLLOVER     43
#define SW_SHOOTER_LANE           44
#define SW_PLAYFIELD_TILT         45


#define SOL_OUTHOLE                 0
#define SOL_LL_DROP_RESET           1
#define SOL_LR_DROP_RESET           2
#define SOL_UL_DROP_RESET           3
#define SOL_UR_DROP_RESET           4
#define SOL_BALL_RAMP_THROWER       5
#define SOL_UPPER_BALL_EJECT        6
#define SOL_SAUCER                  7
#define SOL_RIGHT_MAGNA_SAVE        8
#define SOL_LEFT_MAGNA_SAVE         9
#define SOL_GI_RELAY                10
#define SOL_BELL                    14
#define SOLCONT_COIN_LOCKOUT        15

#define SOL_LEFT_SLING              16
#define SOL_RIGHT_SLING             17 
#define SOL_POP_BUMPER              18


#ifdef RPU_OS_USE_ACCESSORY_LAMP_BOARD
#define MESSAGE_AREA_TOPPER                       1
#define MESSAGE_AREA_SPEAKER                      2
#define MESSAGE_AREA_LEFT_SPEAKER                 3
#define MESSAGE_AREA_RIGHT_SPEAKER                4
#define MESSAGE_AREA_STADIUM                      5
#define MESSAGE_AREA_UNDERCAB                     6
#define MESSAGE_AREA_BACKGLASS                    7
#define MESSAGE_AREA_GI_0                         8
#define MESSAGE_AREA_GI_1                         9
#define MESSAGE_AREA_GI_2                         10
#define MESSAGE_AREA_GI_3                         11
#define MESSAGE_AREA_GI_4                         12
#define SET_COLOR_0                               0
#define SET_COLOR_1                               1
#define SET_COLOR_2                               2
#define SET_TOPPER_BRIGHTNESS                     3
#define SET_SPEAKER_BRIGHTNESS                    4
#define SET_BACKGLASS_BRIGHTNESS                  5
#define SET_STADIUM_BRIGHTNESS                    6
#define SET_UNDERCAB_BRIGHTNESS                   7
#define SET_GI_BRIGHTNESS_0                       8
#define SET_GI_BRIGHTNESS_1                       9
#define SET_GI_BRIGHTNESS_2                       10
#define SET_GI_BRIGHTNESS_3                       11
#define SET_GI_BRIGHTNESS_4                       12
#define TOPPER_PULSE_COLOR_0                      15
#define TOPPER_PULSE_COLOR_1                      16
#define TOPPER_PULSE_COLOR_2                      17
#define TOPPER_FLASH_COLOR_0                      18
#define TOPPER_FLASH_COLOR_1                      19
#define TOPPER_FLASH_COLOR_2                      20
#define TOPPER_LOOP_COLOR_0                       21
#define TOPPER_LOOP_COLOR_1                       22
#define TOPPER_LOOP_COLOR_2                       23
#define TOPPER_LEFT_FLASH_COLOR_0                 24
#define TOPPER_LEFT_FLASH_COLOR_1                 25
#define TOPPER_LEFT_FLASH_COLOR_2                 26
#define TOPPER_RIGHT_FLASH_COLOR_0                27
#define TOPPER_RIGHT_FLASH_COLOR_1                28
#define TOPPER_RIGHT_FLASH_COLOR_2                29
#define TOPPER_LEFT_TO_RIGHT_COLOR_0              30
#define TOPPER_LEFT_TO_RIGHT_COLOR_1              31
#define TOPPER_LEFT_TO_RIGHT_COLOR_2              32
#define TOPPER_RIGHT_TO_LEFT_COLOR_0              33
#define TOPPER_RIGHT_TO_LEFT_COLOR_1              34
#define TOPPER_RIGHT_TO_LEFT_COLOR_2              35
#define TOPPER_SPARKLE_COLOR_0                    36
#define TOPPER_SPARKLE_COLOR_1                    37
#define TOPPER_SPARKLE_COLOR_2                    38
#define TOPPER_FIRE                               39
#define TOPPER_CANDY_PULSE                        40
#define TOPPER_LIGHTNING_0                        41
#define TOPPER_LIGHTNING_1                        42
#define TOPPER_LIGHTNING_2                        43
#define TOPPER_LIGHTNING_3                        44
#define TOPPER_LIGHTNING_4                        45
#define TOPPER_BIG_LIGHTNING_0                    46
#define TOPPER_BIG_LIGHTNING_1                    47
#define LEFT_TO_RIGHT_SPEAKER_COLOR_0             50
#define LEFT_TO_RIGHT_SPEAKER_COLOR_1             51
#define LEFT_TO_RIGHT_SPEAKER_COLOR_2             52
#define RIGHT_TO_LEFT_SPEAKER_COLOR_0             53
#define RIGHT_TO_LEFT_SPEAKER_COLOR_1             54
#define RIGHT_TO_LEFT_SPEAKER_COLOR_2             55
#define BOTH_SPEAKERS_TWO_COLOR_0_1_PULSE         56
#define LEFT_SPEAKER_PULSE_COLOR_0                60
#define LEFT_SPEAKER_PULSE_COLOR_1                61
#define LEFT_SPEAKER_PULSE_COLOR_2                62
#define LEFT_SPEAKER_FLASH_COLOR_0                63
#define LEFT_SPEAKER_FLASH_COLOR_1                64
#define LEFT_SPEAKER_FLASH_COLOR_2                65
#define LEFT_SPEAKER_LOOP_CW_COLOR_0              66
#define LEFT_SPEAKER_LOOP_CW_COLOR_1              67
#define LEFT_SPEAKER_LOOP_CW_COLOR_2              68
#define LEFT_SPEAKER_LOOP_CCW_COLOR_0             69
#define LEFT_SPEAKER_LOOP_CCW_COLOR_1             70
#define LEFT_SPEAKER_LOOP_CCW_COLOR_2             71
#define RIGHT_SPEAKER_PULSE_COLOR_0               75
#define RIGHT_SPEAKER_PULSE_COLOR_1               76
#define RIGHT_SPEAKER_PULSE_COLOR_2               77
#define RIGHT_SPEAKER_FLASH_COLOR_0               78
#define RIGHT_SPEAKER_FLASH_COLOR_1               79
#define RIGHT_SPEAKER_FLASH_COLOR_2               80
#define RIGHT_SPEAKER_LOOP_CW_COLOR_0             81
#define RIGHT_SPEAKER_LOOP_CW_COLOR_1             82
#define RIGHT_SPEAKER_LOOP_CW_COLOR_2             83
#define RIGHT_SPEAKER_LOOP_CCW_COLOR_0            84
#define RIGHT_SPEAKER_LOOP_CCW_COLOR_1            85
#define RIGHT_SPEAKER_LOOP_CCW_COLOR_2            86
#define STADIUM_SET_COLOR_0                       90
#define STADIUM_SET_COLOR_1                       91
#define STADIUM_SET_COLOR_2                       92
#define STADIUM_PULSE_COLOR_0                     93
#define STADIUM_PULSE_COLOR_1                     94
#define STADIUM_PULSE_COLOR_2                     95
#define UNDERCAB_SET_COLOR_0                      120
#define BACKGLASS_SET_SCENE_0                     170
#define GI_0_SET_COLOR                            210
#define GI_0_PULSE_COLOR                          211
#define GI_0_FLICKER_COLOR                        212
#define GI_1_SET_COLOR                            218
#define GI_1_PULSE_COLOR                          219
#define GI_1_FLICKER_COLOR                        220
#define GI_2_SET_COLOR                            226
#define GI_2_PULSE_COLOR                          227
#define GI_2_FLICKER_COLOR                        228
#define GI_2_FLICKER_START_PIXEL                  229
#define GI_2_FLICKER_END_PIXEL                    230
#define GI_3_SET_COLOR                            232
#define GI_4_SET_COLOR                            240
#define CONTROL_MESSAGE_UNSET                     255
#endif


